# Generated by Django 5.2.5 on 2025-11-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('alias', models.CharField(default='', max_length=64)),
                ('alias_required', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_scanned', models.DateTimeField(blank=True, null=True, verbose_name='Last Scanned')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.4, max_digits=5)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=1024)),
                ('discount_text', models.CharField(blank=True, default='', max_length=100)),
                ('thumbnail_file', models.CharField(max_length=2048)),
                ('ordering_priority', models.IntegerField(blank=True, default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('datetime_completed', models.DateTimeField(blank=True, null=True, verbose_name='Date Completed')),
                ('completion_status', models.CharField(default='', max_length=64)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.card')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.product')),
            ],
        ),
    ]
