# Generated by Django 5.2.5 on 2026-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_question', models.CharField(default='Please enter your name', max_length=256)),
            ],
            options={
                'verbose_name': 'Kiosk Settings',
                'verbose_name_plural': 'Kiosk Settings',
            },
        ),
    ]
