# Generated by Django 6.0.6 on 2026-06-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_kiosksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosksettings',
            name='prompt_new_cards',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
